/**
 * NER-LOGIX SIMULATION DATA.
 *
 * Everything in this file is generated by the NER-LOGIX prototype for
 * demonstration. It is NOT government data and is labelled as simulation
 * everywhere it is rendered. Later steps replace it with live system data.
 *
 * Positions reference real district label points so simulated items land in the
 * correct place on the real map.
 */

import { getDistrictCentroid } from "@/services/government/lgdService";
import type {
  Incident,
  OperationalAlert,
  RouteSegment,
  TransportMission,
  Vehicle,
} from "@/types/domain";

/** Offset a district label point slightly so multiple markers stay readable. */
function near(districtId: string, dLng = 0, dLat = 0): [number, number] {
  const c = getDistrictCentroid(districtId);
  if (!c) return [0, 0];
  return [c[0] + dLng, c[1] + dLat];
}

export const SIM_INCIDENTS: Incident[] = [
  {
    id: "INC-2291",
    type: "Landslide",
    severity: "blocked",
    districtId: "east-jaintia-hills",
    position: near("east-jaintia-hills", 0.05, 0.03),
    reportedAt: "09 min ago",
    source: "nerlogix-system",
  },
  {
    id: "INC-2288",
    type: "Flooding",
    severity: "high",
    districtId: "cachar",
    position: near("cachar", -0.08, 0.04),
    reportedAt: "34 min ago",
    source: "nerlogix-system",
  },
  {
    id: "INC-2284",
    type: "Road erosion",
    severity: "moderate",
    districtId: "tinsukia",
    position: near("tinsukia", 0.02, -0.06),
    reportedAt: "01h 12m ago",
    source: "nerlogix-system",
  },
];

export const SIM_VEHICLES: Vehicle[] = [
  {
    id: "LG-114",
    kind: "logistics",
    districtId: "jorhat",
    position: near("jorhat", 0.05, 0.05),
    status: "En route",
    source: "nerlogix-simulation",
  },
  {
    id: "LG-208",
    kind: "logistics",
    districtId: "sonitpur",
    position: near("sonitpur", -0.04, 0.02),
    status: "En route",
    source: "nerlogix-simulation",
  },
  {
    id: "LG-331",
    kind: "logistics",
    districtId: "west-garo-hills",
    position: near("west-garo-hills", 0.03, -0.03),
    status: "Loading",
    source: "nerlogix-simulation",
  },
  {
    id: "MD-051",
    kind: "medical",
    districtId: "kamrup-metropolitan",
    position: near("kamrup-metropolitan", -0.03, -0.02),
    status: "Standby",
    source: "nerlogix-simulation",
  },
  {
    id: "MD-077",
    kind: "medical",
    districtId: "ri-bhoi",
    position: near("ri-bhoi", 0.04, 0.02),
    status: "Transfer",
    source: "nerlogix-simulation",
  },
];

export const SIM_ROUTES: RouteSegment[] = [
  {
    id: "R-01",
    label: "Dibrugarh — Guwahati",
    waypointDistrictIds: ["dibrugarh", "jorhat", "sonitpur", "kamrup-metropolitan"],
    risk: "moderate",
    source: "nerlogix-simulation",
  },
  {
    id: "R-02",
    label: "Shillong — Guwahati",
    waypointDistrictIds: ["east-khasi-hills", "ri-bhoi", "kamrup-metropolitan"],
    risk: "safe",
    source: "nerlogix-simulation",
  },
  {
    id: "R-03",
    label: "Guwahati — Silchar",
    waypointDistrictIds: ["kamrup-metropolitan", "east-jaintia-hills", "cachar"],
    risk: "high",
    source: "nerlogix-simulation",
  },
  {
    id: "R-04",
    label: "Jowai — Silchar",
    waypointDistrictIds: ["east-jaintia-hills", "cachar"],
    risk: "blocked",
    source: "nerlogix-simulation",
  },
  {
    id: "R-05",
    label: "Tura — Guwahati",
    waypointDistrictIds: ["west-garo-hills", "west-khasi-hills", "kamrup-metropolitan"],
    risk: "moderate",
    source: "nerlogix-simulation",
  },
];

export const SIM_MISSIONS: TransportMission[] = [
  {
    code: "MISSION 001",
    type: "Logistics",
    descriptorLabel: "Cargo",
    descriptor: "Essential Supplies",
    origin: "Dibrugarh",
    destination: "Guwahati",
    originDistrictId: "dibrugarh",
    destinationDistrictId: "kamrup-metropolitan",
    status: "En Route",
    progress: 62,
    eta: "04h 20m",
    riskLabel: "Moderate",
    risk: "moderate",
    source: "nerlogix-simulation",
  },
  {
    code: "MISSION 002",
    type: "Medical",
    descriptorLabel: "Service",
    descriptor: "Emergency Medical Transfer",
    origin: "Shillong",
    destination: "Guwahati",
    originDistrictId: "east-khasi-hills",
    destinationDistrictId: "kamrup-metropolitan",
    status: "En Route",
    progress: 41,
    eta: "01h 05m",
    riskLabel: "Safe",
    risk: "safe",
    priority: "Emergency",
    source: "nerlogix-simulation",
  },
  {
    code: "MISSION 003",
    type: "Logistics",
    descriptorLabel: "Cargo",
    descriptor: "Cold-chain Vaccines",
    origin: "Guwahati",
    destination: "Silchar",
    originDistrictId: "kamrup-metropolitan",
    destinationDistrictId: "cachar",
    status: "Rerouting",
    progress: 28,
    eta: "07h 45m",
    riskLabel: "High",
    risk: "high",
    source: "nerlogix-simulation",
  },
  {
    code: "MISSION 004",
    type: "Medical",
    descriptorLabel: "Service",
    descriptor: "Blood Unit Relay",
    origin: "Jorhat",
    destination: "Dibrugarh",
    originDistrictId: "jorhat",
    destinationDistrictId: "dibrugarh",
    status: "En Route",
    progress: 77,
    eta: "00h 55m",
    riskLabel: "Safe",
    risk: "safe",
    source: "nerlogix-simulation",
  },
];

export const SIM_ALERTS: OperationalAlert[] = [
  {
    id: "ALT-4417",
    category: "nerlogix-incident",
    title: "High-risk road segment detected",
    detail: "NH-6 corridor flagged for slope instability; convoy speed restricted.",
    location: "East Jaintia Hills, Meghalaya",
    time: "09 min ago",
    severity: "blocked",
    source: "nerlogix-system",
  },
  {
    id: "ALT-4412",
    category: "nerlogix-incident",
    title: "New incident reported",
    detail: "Road erosion reported near Makum; single-lane movement only.",
    location: "Tinsukia, Assam",
    time: "01h 12m ago",
    severity: "moderate",
    source: "nerlogix-system",
  },
  {
    id: "SIM-0031",
    category: "simulation",
    title: "Medical route priority active",
    detail: "Shillong — Guwahati corridor held under emergency transfer priority.",
    location: "Ri-Bhoi, Meghalaya",
    time: "02h 03m ago",
    severity: "safe",
    source: "nerlogix-simulation",
  },
];

export function incidentsForDistrict(districtId: string): Incident[] {
  return SIM_INCIDENTS.filter((i) => i.districtId === districtId);
}

export function missionsForDistrict(districtId: string): TransportMission[] {
  return SIM_MISSIONS.filter(
    (m) => m.originDistrictId === districtId || m.destinationDistrictId === districtId,
  );
}

export function routeLine(route: RouteSegment): [number, number][] {
  return route.waypointDistrictIds
    .map((id) => getDistrictCentroid(id))
    .filter((c): c is [number, number] => Boolean(c))
    .map(([lng, lat]) => [lat, lng] as [number, number]);
}
